# Generated by Django 2.1.5 on 2019-02-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estate_type', models.CharField(choices=[('house', 'House'), ('flat', 'Flat'), ('investment', 'Investment'), ('plot', 'Plot')], max_length=10)),
            ],
        ),
    ]
