# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Tytuł')),
                ('description', models.TextField(max_length=2000, verbose_name='Opis')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='Lokacja')),
                ('type', models.CharField(choices=[('sell', 'Sprzedaż'), ('rent', 'Wynajem')], max_length=10, verbose_name='Typ ogłoszenia')),
                ('estate', models.CharField(choices=[('plot', 'Działka'), ('investment', 'Inwestycja'), ('flat', 'Mieszkanie'), ('house', 'Dom')], max_length=12, verbose_name='Typ nieruchomości')),
                ('size', models.DecimalField(decimal_places=1, max_digits=8, verbose_name='Rozmiar')),
                ('plot_size', models.DecimalField(decimal_places=1, default=1, max_digits=8, verbose_name='Rozmiar działki')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Oferty',
                'ordering': ('type',),
            },
        ),
    ]
