# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 15:34
from __future__ import unicode_literals

import adverts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_auto_20170219_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Zdjęcie', 'verbose_name_plural': 'Zdjęcia'},
        ),
        migrations.AddField(
            model_name='images',
            name='advert',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='adverts.Advert'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='estate',
            field=models.CharField(choices=[('plot', 'Działka'), ('investment', 'Inwestycja'), ('flat', 'Mieszkanie'), ('house', 'Dom')], max_length=12, verbose_name='Typ nieruchomości'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(height_field='height_field', upload_to=adverts.models.upload_directory, verbose_name='Zdjęcie', width_field='width_field'),
        ),
    ]
