# Generated by Django 2.1.5 on 2019-02-09 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_advert_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='location',
            new_name='address',
        ),
    ]
