# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_auto_20170219_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='thumbnail',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advert',
            name='estate',
            field=models.CharField(choices=[('house', 'Dom'), ('plot', 'Działka'), ('flat', 'Mieszkanie'), ('investment', 'Inwestycja')], max_length=12, verbose_name='Typ nieruchomości'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='type',
            field=models.CharField(choices=[('rent', 'Wynajem'), ('sell', 'Sprzedaż')], max_length=10, verbose_name='Typ ogłoszenia'),
        ),
    ]
