# Generated by Django 2.1.5 on 2019-01-28 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0004_auto_20170219_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertDetail',
            fields=[
                ('advert_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adverts.Advert')),
                ('heating', models.CharField(blank=True, choices=[('gas', 'Gazowe'), ('coal', 'Węglowe'), ('electric', 'Elektryczne'), ('city', 'Miejskie'), ('furnace', 'Kominkowe'), ('diff', 'inne')], max_length=10, null=True, verbose_name='Ogrzewanie')),
                ('windows', models.CharField(blank=True, choices=[('wooden', 'Drewniane'), ('plastic', 'Plastikowe')], max_length=8, null=True, verbose_name='Okna')),
                ('furniture', models.CharField(blank=True, choices=[('none', 'Brak'), ('half', 'Kuchnia i łazienka'), ('full', 'Pełne')], max_length=4, null=True, verbose_name='Umeblowanie')),
                ('balcony', models.BooleanField(blank=True, verbose_name='Balkon')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Oferty',
                'ordering': ('type',),
            },
            bases=('adverts.advert',),
        ),
        migrations.AlterModelOptions(
            name='advert',
            options={},
        ),
        migrations.AlterField(
            model_name='advert',
            name='plot_size',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='Rozmiar działki (m2)'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena (zł)'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='size',
            field=models.DecimalField(decimal_places=1, max_digits=8, verbose_name='Rozmiar (m2)'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='type',
            field=models.CharField(choices=[('sell', 'Sprzedaż'), ('rent', 'Wynajem')], max_length=10, verbose_name='Typ ogłoszenia'),
        ),
        migrations.AlterField(
            model_name='images',
            name='advert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='adverts.Advert'),
        ),
        migrations.AlterField(
            model_name='images',
            name='thumbnail',
            field=models.BooleanField(default=False, verbose_name='Miniaturka'),
        ),
    ]
