# Generated by Django 2.1.5 on 2019-01-29 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adverts', '0006_advert_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, null=True)),
                ('created', models.DateTimeField(null=True)),
                ('on_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='advert',
            name='details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='adverts.AdvertDetail'),
        ),
        migrations.AddField(
            model_name='advertdetail',
            name='statues',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adverts.AdvertStatus'),
        ),
    ]
