# Generated by Django 2.1.5 on 2019-02-09 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_auto_20190209_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickFilterLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=16)),
                ('lng', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AddField(
            model_name='quickfilterlocation',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.City'),
        ),
    ]
