# Generated by Django 2.1.5 on 2019-02-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_auto_20190209_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickfilterlocation',
            name='code',
            field=models.CharField(default='XD', max_length=20),
            preserve_default=False,
        ),
    ]
